alter table public.account_import_batches add constraint account_import_batches_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.account_import_batches add constraint account_import_batches_pkey PRIMARY KEY (id);
alter table public.accounts add constraint accounts_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.accounts add constraint accounts_pkey PRIMARY KEY (id);
alter table public.accounts add constraint accounts_company_id_account_nr_key UNIQUE (company_id, account_nr);
alter table public.agi_deklarationer add constraint agi_deklarationer_pkey PRIMARY KEY (id);
alter table public.agi_deklarationer add constraint agi_deklarationer_company_id_period_key UNIQUE (company_id, period);
alter table public.ai_bokforing_logg add constraint ai_bokforing_logg_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.ai_bokforing_logg add constraint ai_bokforing_logg_document_id_fkey FOREIGN KEY (document_id) REFERENCES documents(id) ON DELETE SET NULL;
alter table public.ai_bokforing_logg add constraint ai_bokforing_logg_verifikation_id_fkey FOREIGN KEY (verifikation_id) REFERENCES verifikationer(id) ON DELETE SET NULL;
alter table public.ai_bokforing_logg add constraint ai_bokforing_logg_pkey PRIMARY KEY (id);
alter table public.ai_call_log add constraint ai_call_log_pkey PRIMARY KEY (id);
alter table public.ai_checklista_korningar add constraint ai_checklista_korningar_antal_ai_anrop_check CHECK ((antal_ai_anrop >= 0));
alter table public.ai_checklista_korningar add constraint ai_checklista_korningar_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.ai_checklista_korningar add constraint ai_checklista_korningar_pkey PRIMARY KEY (id);
alter table public.ai_cooldowns add constraint ai_cooldowns_scope_check CHECK ((scope = ANY (ARRAY['document'::text, 'user'::text, 'company'::text])));
alter table public.ai_cooldowns add constraint ai_cooldowns_pkey PRIMARY KEY (scope, scope_key);
alter table public.ai_error_log add constraint ai_error_log_pkey PRIMARY KEY (id);
alter table public.ai_usage_log add constraint ai_usage_log_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.ai_usage_log add constraint ai_usage_log_pkey PRIMARY KEY (id);
alter table public.aml_flags add constraint aml_flags_allvarlighet_check CHECK ((allvarlighet = ANY (ARRAY['lag'::text, 'normal'::text, 'hog'::text])));
alter table public.aml_flags add constraint aml_flags_status_check CHECK ((status = ANY (ARRAY['oppen'::text, 'granskad'::text, 'rapporterad'::text, 'avfardad'::text])));
alter table public.aml_flags add constraint aml_flags_typ_check CHECK ((typ = ANY (ARRAY['kontantgrans'::text, 'strukturering'::text, 'sanktionstraff'::text, 'avvikande_monster'::text, 'hogrisk_land'::text, 'kyc_saknas'::text, 'manuell'::text])));
alter table public.aml_flags add constraint aml_flags_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id);
alter table public.aml_flags add constraint aml_flags_pkey PRIMARY KEY (id);
alter table public.aml_flags add constraint aml_flags_company_id_dedup_nyckel_key UNIQUE (company_id, dedup_nyckel);
alter table public.aml_installningar add constraint aml_installningar_id_check CHECK (id);
alter table public.aml_installningar add constraint aml_installningar_byra_bolag_id_fkey FOREIGN KEY (byra_bolag_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.aml_installningar add constraint aml_installningar_pkey PRIMARY KEY (byra_bolag_id);
alter table public.annual_report_draft_sections add constraint annual_report_draft_sections_review_status_check CHECK ((review_status = ANY (ARRAY['needs_review'::text, 'reviewed'::text, 'approved'::text, 'rejected'::text])));
alter table public.annual_report_draft_sections add constraint annual_report_draft_sections_section_key_check CHECK ((section_key = ANY (ARRAY['forvaltningsberattelse'::text, 'resultatrakning'::text, 'balansrakning'::text, 'noter'::text, 'faststallelseintyg'::text, 'underskriftssida'::text])));
alter table public.annual_report_draft_sections add constraint annual_report_draft_sections_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.annual_report_draft_sections add constraint annual_report_draft_sections_draft_id_fkey FOREIGN KEY (draft_id) REFERENCES annual_report_drafts(id) ON DELETE CASCADE;
alter table public.annual_report_draft_sections add constraint annual_report_draft_sections_pkey PRIMARY KEY (id);
alter table public.annual_report_draft_sections add constraint annual_report_draft_sections_draft_id_section_key_key UNIQUE (draft_id, section_key);
alter table public.annual_report_drafts add constraint annual_report_drafts_status_check CHECK ((status = ANY (ARRAY['draft'::text, 'needs_review'::text, 'reviewed'::text, 'approved'::text, 'rejected'::text, 'locked'::text])));
alter table public.annual_report_drafts add constraint annual_report_drafts_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.annual_report_drafts add constraint annual_report_drafts_engagement_id_fkey FOREIGN KEY (engagement_id) REFERENCES bokslut_engagements(id) ON DELETE CASCADE;
alter table public.annual_report_drafts add constraint annual_report_drafts_fiscal_year_id_fkey FOREIGN KEY (fiscal_year_id) REFERENCES fiscal_years(id) ON DELETE SET NULL;
alter table public.annual_report_drafts add constraint annual_report_drafts_pkey PRIMARY KEY (id);
alter table public.annual_report_drafts add constraint annual_report_drafts_engagement_id_key UNIQUE (engagement_id);
alter table public.annual_report_exports add constraint annual_report_exports_export_type_check CHECK ((export_type = ANY (ARRAY['review_pdf'::text, 'html_preview'::text, 'archive_pdf'::text])));
alter table public.annual_report_exports add constraint annual_report_exports_quality_status_check CHECK ((quality_status = ANY (ARRAY['not_checked'::text, 'passed'::text, 'failed'::text, 'warning'::text])));
alter table public.annual_report_exports add constraint annual_report_exports_status_check CHECK ((status = ANY (ARRAY['generating'::text, 'ready'::text, 'failed'::text])));
alter table public.annual_report_exports add constraint annual_report_exports_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.annual_report_exports add constraint annual_report_exports_draft_id_fkey FOREIGN KEY (draft_id) REFERENCES annual_report_drafts(id) ON DELETE CASCADE;
alter table public.annual_report_exports add constraint annual_report_exports_engagement_id_fkey FOREIGN KEY (engagement_id) REFERENCES bokslut_engagements(id) ON DELETE CASCADE;
alter table public.annual_report_exports add constraint annual_report_exports_pkey PRIMARY KEY (id);
alter table public.annual_report_validation_items add constraint annual_report_validation_items_severity_check CHECK ((severity = ANY (ARRAY['info'::text, 'warning'::text, 'high'::text, 'critical'::text])));
alter table public.annual_report_validation_items add constraint annual_report_validation_items_status_check CHECK ((status = ANY (ARRAY['open'::text, 'resolved'::text, 'ignored'::text])));
alter table public.annual_report_validation_items add constraint annual_report_validation_items_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.annual_report_validation_items add constraint annual_report_validation_items_draft_id_fkey FOREIGN KEY (draft_id) REFERENCES annual_report_drafts(id) ON DELETE CASCADE;
alter table public.annual_report_validation_items add constraint annual_report_validation_items_engagement_id_fkey FOREIGN KEY (engagement_id) REFERENCES bokslut_engagements(id) ON DELETE CASCADE;
alter table public.annual_report_validation_items add constraint annual_report_validation_items_section_id_fkey FOREIGN KEY (section_id) REFERENCES annual_report_draft_sections(id) ON DELETE SET NULL;
alter table public.annual_report_validation_items add constraint annual_report_validation_items_pkey PRIMARY KEY (id);
alter table public.annual_report_validation_items add constraint annual_report_validation_items_draft_id_validation_key_key UNIQUE (draft_id, validation_key);
alter table public.arkiv_filer add constraint arkiv_filer_kalla_check CHECK ((kalla = ANY (ARRAY['uppladdad'::text, 'underlag'::text, 'moms'::text, 'agi'::text, 'sie'::text, 'arsredovisning'::text, 'arkivexport'::text])));
alter table public.arkiv_filer add constraint arkiv_filer_kalla_ck CHECK (((document_id IS NOT NULL) OR (storage_path IS NOT NULL)));
alter table public.arkiv_filer add constraint arkiv_filer_sokvag_ck CHECK (((storage_path IS NULL) OR (storage_path ~~ ((((company_id)::text || '/'::text) || (mapp_id)::text) || '/%'::text))));
alter table public.arkiv_filer add constraint arkiv_filer_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.arkiv_filer add constraint arkiv_filer_document_id_fkey FOREIGN KEY (document_id) REFERENCES documents(id) ON DELETE CASCADE;
alter table public.arkiv_filer add constraint arkiv_filer_mapp_id_fkey FOREIGN KEY (mapp_id) REFERENCES arkiv_mappar(id) ON DELETE CASCADE;
alter table public.arkiv_filer add constraint arkiv_filer_pkey PRIMARY KEY (id);
alter table public.arkiv_mappar add constraint arkiv_mappar_gallringsregel_check CHECK ((gallringsregel = ANY (ARRAY['ingen'::text, 'bfl_7ar'::text, 'ptl_5ar'::text, 'gdpr_gallras'::text])));
alter table public.arkiv_mappar add constraint arkiv_mappar_namn_check CHECK (((length(btrim(namn)) >= 1) AND (length(btrim(namn)) <= 80)));
alter table public.arkiv_mappar add constraint arkiv_mappar_synlighet_check CHECK ((synlighet = ANY (ARRAY['byra'::text, 'kund'::text, 'kund_skriv'::text])));
alter table public.arkiv_mappar add constraint arkiv_mappar_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.arkiv_mappar add constraint arkiv_mappar_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES arkiv_mappar(id) ON DELETE CASCADE;
alter table public.arkiv_mappar add constraint arkiv_mappar_pkey PRIMARY KEY (id);
alter table public.article_templates add constraint article_templates_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.article_templates add constraint article_templates_pkey PRIMARY KEY (id);
alter table public.assistent_logg add constraint assistent_logg_status_check CHECK ((status = ANY (ARRAY['pagaende'::text, 'klar'::text, 'fel'::text])));
alter table public.assistent_logg add constraint assistent_logg_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.assistent_logg add constraint assistent_logg_pkey PRIMARY KEY (id);
alter table public.audit_log add constraint audit_log_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.audit_log add constraint audit_log_pkey PRIMARY KEY (id);
alter table public.bank_accounts add constraint bank_accounts_valuta_chk CHECK (((valuta IS NULL) OR (valuta = ANY (ARRAY['SEK'::text, 'USD'::text, 'GBP'::text, 'EUR'::text]))));
alter table public.bank_accounts add constraint bank_accounts_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.bank_accounts add constraint bank_accounts_pkey PRIMARY KEY (id);
alter table public.bank_transactions add constraint bank_transactions_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.bank_transactions add constraint bank_transactions_verifikation_id_fkey FOREIGN KEY (verifikation_id) REFERENCES verifikationer(id) ON DELETE SET NULL;
alter table public.bank_transactions add constraint bank_transactions_pkey PRIMARY KEY (id);
alter table public.bas_accounts add constraint bas_accounts_pkey PRIMARY KEY (account_nr);
alter table public.beta_ansokningar add constraint beta_ansokningar_meddelande_check CHECK ((char_length(meddelande) <= 2000));
alter table public.beta_ansokningar add constraint beta_ansokningar_status_check CHECK ((status = ANY (ARRAY['vantar'::text, 'godkand'::text, 'avvisad'::text])));
alter table public.beta_ansokningar add constraint beta_ansokningar_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE SET NULL;
alter table public.beta_ansokningar add constraint beta_ansokningar_pkey PRIMARY KEY (id);
alter table public.bokslut_ai_suggestions add constraint bokslut_ai_suggestions_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.bokslut_ai_suggestions add constraint bokslut_ai_suggestions_engagement_id_fkey FOREIGN KEY (engagement_id) REFERENCES bokslut_engagements(id) ON DELETE CASCADE;
alter table public.bokslut_ai_suggestions add constraint bokslut_ai_suggestions_related_attachment_id_fkey FOREIGN KEY (related_attachment_id) REFERENCES bokslut_attachments(id) ON DELETE SET NULL;
alter table public.bokslut_ai_suggestions add constraint bokslut_ai_suggestions_related_check_id_fkey FOREIGN KEY (related_check_id) REFERENCES bokslut_checks(id) ON DELETE SET NULL;
alter table public.bokslut_ai_suggestions add constraint bokslut_ai_suggestions_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES auth.users(id);
alter table public.bokslut_ai_suggestions add constraint bokslut_ai_suggestions_pkey PRIMARY KEY (id);
alter table public.bokslut_attachments add constraint bokslut_attachments_check_id_fkey FOREIGN KEY (check_id) REFERENCES bokslut_checks(id) ON DELETE SET NULL;
alter table public.bokslut_attachments add constraint bokslut_attachments_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.bokslut_attachments add constraint bokslut_attachments_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id);
alter table public.bokslut_attachments add constraint bokslut_attachments_engagement_id_fkey FOREIGN KEY (engagement_id) REFERENCES bokslut_engagements(id) ON DELETE CASCADE;
alter table public.bokslut_attachments add constraint bokslut_attachments_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES auth.users(id);
alter table public.bokslut_attachments add constraint bokslut_attachments_pkey PRIMARY KEY (id);
alter table public.bokslut_audit_log add constraint bokslut_audit_log_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.bokslut_audit_log add constraint bokslut_audit_log_engagement_id_fkey FOREIGN KEY (engagement_id) REFERENCES bokslut_engagements(id) ON DELETE CASCADE;
alter table public.bokslut_audit_log add constraint bokslut_audit_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id);
alter table public.bokslut_audit_log add constraint bokslut_audit_log_pkey PRIMARY KEY (id);
alter table public.bokslut_checks add constraint bokslut_checks_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES auth.users(id);
alter table public.bokslut_checks add constraint bokslut_checks_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.bokslut_checks add constraint bokslut_checks_engagement_id_fkey FOREIGN KEY (engagement_id) REFERENCES bokslut_engagements(id) ON DELETE CASCADE;
alter table public.bokslut_checks add constraint bokslut_checks_resolved_by_fkey FOREIGN KEY (resolved_by) REFERENCES auth.users(id);
alter table public.bokslut_checks add constraint bokslut_checks_pkey PRIMARY KEY (id);
alter table public.bokslut_denied_log add constraint bokslut_denied_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.bokslut_denied_log add constraint bokslut_denied_log_pkey PRIMARY KEY (id);
alter table public.bokslut_engagements add constraint bokslut_engagements_ansvarig_user_id_fkey FOREIGN KEY (ansvarig_user_id) REFERENCES auth.users(id);
alter table public.bokslut_engagements add constraint bokslut_engagements_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.bokslut_engagements add constraint bokslut_engagements_fiscal_year_id_fkey FOREIGN KEY (fiscal_year_id) REFERENCES fiscal_years(id) ON DELETE CASCADE;
alter table public.bokslut_engagements add constraint bokslut_engagements_pkey PRIMARY KEY (id);
alter table public.bokslut_engagements add constraint bokslut_engagements_company_id_fiscal_year_id_key UNIQUE (company_id, fiscal_year_id);
alter table public.bokslut_sync_operations add constraint bokslut_sync_ops_entity_chk CHECK ((entity_type = 'bokslut_check'::text));
alter table public.bokslut_sync_operations add constraint bokslut_sync_ops_optype_chk CHECK ((operation_type = ANY (ARRAY['upsert_comment'::text, 'clear_comment'::text, 'overwrite_comment'::text])));
alter table public.bokslut_sync_operations add constraint bokslut_sync_ops_status_chk CHECK ((status = ANY (ARRAY['claimed'::text, 'final'::text])));
alter table public.bokslut_sync_operations add constraint bokslut_sync_operations_pkey PRIMARY KEY (id);
alter table public.bokslut_sync_operations add constraint bokslut_sync_ops_uniq UNIQUE (user_id, idempotency_key);
alter table public.bookkeeping_templates add constraint bookkeeping_templates_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.bookkeeping_templates add constraint bookkeeping_templates_pkey PRIMARY KEY (id);
alter table public.byra_installningar add constraint byra_installningar_typer_check CHECK ((standard_uppdragstyper <@ ARRAY['lopande_bokforing'::text, 'momsdeklaration'::text, 'lon_agi'::text, 'bokslut'::text, 'arsredovisning'::text, 'inkomstdeklaration'::text]));
alter table public.byra_installningar add constraint byra_installningar_byra_bolag_id_fkey FOREIGN KEY (byra_bolag_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.byra_installningar add constraint byra_installningar_pkey PRIMARY KEY (byra_bolag_id);
alter table public.byra_klient add constraint byra_klient_check CHECK ((byra_bolag_id <> klient_bolag_id));
alter table public.byra_klient add constraint byra_klient_status_check CHECK ((status = ANY (ARRAY['onboarding'::text, 'vantar_godkannande'::text, 'aktiv'::text, 'inaktiv'::text])));
alter table public.byra_klient add constraint byra_klient_byra_bolag_id_fkey FOREIGN KEY (byra_bolag_id) REFERENCES companies(id) ON DELETE RESTRICT;
alter table public.byra_klient add constraint byra_klient_klient_bolag_id_fkey FOREIGN KEY (klient_bolag_id) REFERENCES companies(id) ON DELETE RESTRICT;
alter table public.byra_klient add constraint byra_klient_pkey PRIMARY KEY (id);
alter table public.byra_klient add constraint byra_klient_byra_bolag_id_klient_bolag_id_key UNIQUE (byra_bolag_id, klient_bolag_id);
alter table public.byra_medlemmar add constraint byra_medlemmar_pkey PRIMARY KEY (user_id);
alter table public.byra_medlemskap add constraint byra_medlemskap_roll_check CHECK ((roll = ANY (ARRAY['admin'::text, 'konsult'::text])));
alter table public.byra_medlemskap add constraint byra_medlemskap_byra_bolag_id_fkey FOREIGN KEY (byra_bolag_id) REFERENCES companies(id) ON DELETE RESTRICT;
alter table public.byra_medlemskap add constraint byra_medlemskap_pkey PRIMARY KEY (id);
alter table public.byra_medlemskap add constraint byra_medlemskap_byra_bolag_id_anvandare_id_key UNIQUE (byra_bolag_id, anvandare_id);
alter table public.companies add constraint companies_abonnemang_status_check CHECK ((abonnemang_status = ANY (ARRAY['testperiod'::text, 'aktiv'::text, 'pausad'::text])));
alter table public.companies add constraint companies_foretagsform_check CHECK (((foretagsform IS NULL) OR (foretagsform = ANY (ARRAY['Aktiebolag'::text, 'Enskild näringsidkare'::text, 'Handelsbolag/Kommanditbolag'::text, 'Ekonomisk förening'::text, 'Ideell förening'::text, 'Bostadsrättsförening'::text, 'Övrigt'::text]))));
alter table public.companies add constraint companies_service_state_check CHECK ((service_state = ANY (ARRAY['active'::text, 'paused'::text, 'blocked'::text])));
alter table public.companies add constraint companies_valuta_chk CHECK (((valuta IS NULL) OR (valuta = ANY (ARRAY['SEK'::text, 'USD'::text, 'GBP'::text, 'EUR'::text]))));
alter table public.companies add constraint companies_pkey PRIMARY KEY (id);
alter table public.company_ai_features add constraint company_ai_features_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.company_ai_features add constraint company_ai_features_pkey PRIMARY KEY (company_id, feature_key);
alter table public.company_invites add constraint company_invites_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.company_invites add constraint company_invites_invited_by_fkey FOREIGN KEY (invited_by) REFERENCES auth.users(id);
alter table public.company_invites add constraint company_invites_pkey PRIMARY KEY (id);
alter table public.company_lookup_cache add constraint company_lookup_cache_pkey PRIMARY KEY (org_nr);
alter table public.company_lookup_rate add constraint company_lookup_rate_pkey PRIMARY KEY (user_id);
alter table public.company_subscriptions add constraint company_subscriptions_billing_period_check CHECK ((billing_period = ANY (ARRAY['monthly'::text, 'yearly'::text, 'trial'::text])));
alter table public.company_subscriptions add constraint company_subscriptions_status_check CHECK ((status = ANY (ARRAY['trial'::text, 'active'::text, 'past_due'::text, 'suspended'::text, 'cancelled'::text, 'expired'::text])));
alter table public.company_subscriptions add constraint company_subscriptions_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.company_subscriptions add constraint company_subscriptions_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES subscription_plans(id);
alter table public.company_subscriptions add constraint company_subscriptions_pkey PRIMARY KEY (id);
alter table public.company_subscriptions add constraint company_subscriptions_company_id_key UNIQUE (company_id);
alter table public.customers add constraint customers_kundtyp_chk CHECK ((kundtyp = ANY (ARRAY['foretag'::text, 'privat'::text])));
alter table public.customers add constraint customers_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.customers add constraint customers_pkey PRIMARY KEY (id);
alter table public.deadline_regel add constraint deadline_regel_bolagsform_check CHECK ((bolagsform = ANY (ARRAY['Aktiebolag'::text, 'Enskild näringsidkare'::text])));
alter table public.deadline_regel add constraint deadline_regel_uppgiftstyp_check CHECK ((uppgiftstyp = ANY (ARRAY['lopande_bokforing'::text, 'momsdeklaration'::text, 'lon_agi'::text, 'bokslut'::text, 'arsredovisning'::text, 'inkomstdeklaration'::text])));
alter table public.deadline_regel add constraint deadline_regel_pkey PRIMARY KEY (id);
alter table public.documents add constraint documents_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.documents add constraint documents_verifikation_id_fkey FOREIGN KEY (verifikation_id) REFERENCES verifikationer(id) ON DELETE SET NULL;
alter table public.documents add constraint documents_pkey PRIMARY KEY (id);
alter table public.download_audit_log add constraint download_audit_log_pkey PRIMARY KEY (id);
alter table public.employees add constraint employees_pkey PRIMARY KEY (id);
alter table public.extraction_corrections add constraint extraction_corrections_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.extraction_corrections add constraint extraction_corrections_document_id_fkey FOREIGN KEY (document_id) REFERENCES documents(id) ON DELETE SET NULL;
alter table public.extraction_corrections add constraint extraction_corrections_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE SET NULL;
alter table public.extraction_corrections add constraint extraction_corrections_pkey PRIMARY KEY (id);
alter table public.fiscal_years add constraint fiscal_years_bfl_check CHECK (((end_date > start_date) AND (EXTRACT(day FROM start_date) = (1)::numeric) AND (end_date = ((date_trunc('month'::text, (end_date)::timestamp without time zone) + '1 mon -1 days'::interval))::date) AND (end_date < (start_date + '1 year 6 mons'::interval))));
alter table public.fiscal_years add constraint fiscal_years_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.fiscal_years add constraint fiscal_years_pkey PRIMARY KEY (id);
alter table public.fiscal_years add constraint fiscal_years_ingen_overlappning EXCLUDE USING gist (company_id WITH =, daterange(start_date, end_date, '[]'::text) WITH &&);
alter table public.help_feedback add constraint help_feedback_pkey PRIMARY KEY (id);
alter table public.inbound_email_log add constraint inbound_email_log_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE SET NULL;
alter table public.inbound_email_log add constraint inbound_email_log_pkey PRIMARY KEY (id);
alter table public.inbox_addresses add constraint inbox_addresses_inbox_type_check CHECK ((inbox_type = ANY (ARRAY['underlag'::text, 'kvitto'::text, 'leverantorsfaktura'::text, 'dokument'::text, 'avtal'::text])));
alter table public.inbox_addresses add constraint inbox_addresses_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.inbox_addresses add constraint inbox_addresses_pkey PRIMARY KEY (id);
alter table public.inbox_addresses add constraint inbox_addresses_company_id_inbox_type_key UNIQUE (company_id, inbox_type);
alter table public.inbox_addresses add constraint inbox_addresses_email_address_key UNIQUE (email_address);
alter table public.ink2_deklarationstidpunkt add constraint ink2_deklarationstidpunkt_bokslutsmanad_fran_check CHECK (((bokslutsmanad_fran >= 1) AND (bokslutsmanad_fran <= 12)));
alter table public.ink2_deklarationstidpunkt add constraint ink2_deklarationstidpunkt_bokslutsmanad_till_check CHECK (((bokslutsmanad_till >= 1) AND (bokslutsmanad_till <= 12)));
alter table public.ink2_deklarationstidpunkt add constraint ink2_deklarationstidpunkt_pkey PRIMARY KEY (id);
alter table public.ink2_deklarationstidpunkt add constraint ink2_deklarationstidpunkt_bokslutsar_bokslutsmanad_fran_key UNIQUE (bokslutsar, bokslutsmanad_fran);
alter table public.inkommande_gods add constraint inkommande_gods_status_check CHECK ((status = ANY (ARRAY['paborjad'::text, 'slutford'::text, 'makulerad'::text])));
alter table public.inkommande_gods add constraint inkommande_gods_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.inkommande_gods add constraint inkommande_gods_leverans_id_fkey FOREIGN KEY (leverans_id) REFERENCES lager_leveranser(id) ON DELETE SET NULL;
alter table public.inkommande_gods add constraint inkommande_gods_order_id_fkey FOREIGN KEY (order_id) REFERENCES inkopsordrar(id) ON DELETE SET NULL;
alter table public.inkommande_gods add constraint inkommande_gods_pkey PRIMARY KEY (id);
alter table public.inkommande_gods add constraint inkommande_gods_company_id_godsnr_key UNIQUE (company_id, godsnr);
alter table public.inkopsorder_rader add constraint inkopsorder_rader_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.inkopsorder_rader add constraint inkopsorder_rader_order_id_fkey FOREIGN KEY (order_id) REFERENCES inkopsordrar(id) ON DELETE CASCADE;
alter table public.inkopsorder_rader add constraint inkopsorder_rader_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE;
alter table public.inkopsorder_rader add constraint inkopsorder_rader_pkey PRIMARY KEY (id);
alter table public.inkopsordrar add constraint inkopsordrar_status_check CHECK ((status = ANY (ARRAY['ej_skickad'::text, 'skickad'::text, 'fullt_mottagen'::text, 'makulerad'::text])));
alter table public.inkopsordrar add constraint inkopsordrar_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.inkopsordrar add constraint inkopsordrar_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE SET NULL;
alter table public.inkopsordrar add constraint inkopsordrar_pkey PRIMARY KEY (id);
alter table public.inkopsordrar add constraint inkopsordrar_company_id_ordernr_key UNIQUE (company_id, ordernr);
alter table public.interna_nycklar add constraint interna_nycklar_pkey PRIMARY KEY (namn);
alter table public.invoice_rows add constraint invoice_rows_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES invoices(id) ON DELETE CASCADE;
alter table public.invoice_rows add constraint invoice_rows_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE SET NULL;
alter table public.invoice_rows add constraint invoice_rows_pkey PRIMARY KEY (id);
alter table public.invoices add constraint invoices_typ_check CHECK ((typ = ANY (ARRAY['faktura'::text, 'kreditfaktura'::text])));
alter table public.invoices add constraint invoices_betalning_ver_id_fkey FOREIGN KEY (betalning_ver_id) REFERENCES verifikationer(id) ON DELETE SET NULL;
alter table public.invoices add constraint invoices_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.invoices add constraint invoices_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES customers(id);
alter table public.invoices add constraint invoices_krediterar_id_fkey FOREIGN KEY (krediterar_id) REFERENCES invoices(id);
alter table public.invoices add constraint invoices_verifikation_id_fkey FOREIGN KEY (verifikation_id) REFERENCES verifikationer(id) ON DELETE SET NULL;
alter table public.invoices add constraint invoices_pkey PRIMARY KEY (id);
alter table public.invoices add constraint invoices_company_id_invoice_nr_key UNIQUE (company_id, invoice_nr);
alter table public.kivra_utskick add constraint kivra_utskick_status_check CHECK ((status = ANY (ARRAY['skickad'::text, 'misslyckad'::text])));
alter table public.kivra_utskick add constraint kivra_utskick_typ_check CHECK ((typ = ANY (ARRAY['faktura'::text, 'lonespec'::text])));
alter table public.kivra_utskick add constraint kivra_utskick_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id);
alter table public.kivra_utskick add constraint kivra_utskick_pkey PRIMARY KEY (id);
alter table public.konsol_abonnemangsfakturor add constraint konsol_abonnemangsfakturor_belopp_ore_check CHECK ((belopp_ore >= 0));
alter table public.konsol_abonnemangsfakturor add constraint konsol_abonnemangsfakturor_status_check CHECK ((status = ANY (ARRAY['fakturerad'::text, 'betald'::text, 'forfallen'::text])));
alter table public.konsol_abonnemangsfakturor add constraint konsol_abonnemangsfakturor_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.konsol_abonnemangsfakturor add constraint konsol_abonnemangsfakturor_pkey PRIMARY KEY (id);
alter table public.konsol_arenden add constraint konsol_arenden_beskrivning_check CHECK ((char_length(beskrivning) <= 4000));
alter table public.konsol_arenden add constraint konsol_arenden_prioritet_check CHECK ((prioritet = ANY (ARRAY['lag'::text, 'normal'::text, 'hog'::text])));
alter table public.konsol_arenden add constraint konsol_arenden_rubrik_check CHECK (((char_length(rubrik) >= 1) AND (char_length(rubrik) <= 200)));
alter table public.konsol_arenden add constraint konsol_arenden_status_check CHECK ((status = ANY (ARRAY['oppen'::text, 'pagar'::text, 'vantar_pa_kund'::text, 'lost'::text])));
alter table public.konsol_arenden add constraint konsol_arenden_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.konsol_arenden add constraint konsol_arenden_pkey PRIMARY KEY (id);
alter table public.konsol_audit_logg add constraint konsol_audit_logg_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE SET NULL;
alter table public.konsol_audit_logg add constraint konsol_audit_logg_pkey PRIMARY KEY (id);
alter table public.konsol_kundanteckningar add constraint konsol_kundanteckningar_innehall_check CHECK (((char_length(innehall) >= 1) AND (char_length(innehall) <= 4000)));
alter table public.konsol_kundanteckningar add constraint konsol_kundanteckningar_typ_check CHECK ((typ = ANY (ARRAY['allmant'::text, 'support'::text, 'uppfoljning'::text])));
alter table public.konsol_kundanteckningar add constraint konsol_kundanteckningar_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.konsol_kundanteckningar add constraint konsol_kundanteckningar_pkey PRIMARY KEY (id);
alter table public.konsol_kundprofiler add constraint konsol_kundprofiler_kundtyp_check CHECK ((kundtyp = ANY (ARRAY['foretag'::text, 'redovisningsbyra'::text, 'partner'::text])));
alter table public.konsol_kundprofiler add constraint konsol_kundprofiler_manadspris_ore_check CHECK ((manadspris_ore >= 0));
alter table public.konsol_kundprofiler add constraint konsol_kundprofiler_prisplan_check CHECK ((prisplan = ANY (ARRAY['start'::text, 'standard'::text, 'pro'::text, 'byra'::text])));
alter table public.konsol_kundprofiler add constraint konsol_kundprofiler_rabatt_check CHECK (((rabatt_procent >= 0) AND (rabatt_procent <= 100)));
alter table public.konsol_kundprofiler add constraint konsol_kundprofiler_testperiod_check CHECK ((testperiod_manader = ANY (ARRAY[1, 2, 3, 6])));
alter table public.konsol_kundprofiler add constraint konsol_kundprofiler_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.konsol_kundprofiler add constraint konsol_kundprofiler_pkey PRIMARY KEY (company_id);
alter table public.konsol_livscykel_steg add constraint konsol_livscykel_steg_notering_check CHECK ((char_length(notering) <= 2000));
alter table public.konsol_livscykel_steg add constraint konsol_livscykel_steg_status_check CHECK ((status = ANY (ARRAY['ej_paborjad'::text, 'pagar'::text, 'klar'::text, 'ej_relevant'::text])));
alter table public.konsol_livscykel_steg add constraint konsol_livscykel_steg_steg_key_check CHECK ((steg_key ~ '^[a-z_]{2,40}$'::text));
alter table public.konsol_livscykel_steg add constraint konsol_livscykel_steg_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.konsol_livscykel_steg add constraint konsol_livscykel_steg_pkey PRIMARY KEY (id);
alter table public.konsol_livscykel_steg add constraint konsol_livscykel_steg_company_id_steg_key_key UNIQUE (company_id, steg_key);
alter table public.konsol_support_samtycken add constraint konsol_support_samtycken_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.konsol_support_samtycken add constraint konsol_support_samtycken_pkey PRIMARY KEY (id);
alter table public.kyc_assessments add constraint kyc_assessments_riskklass_check CHECK ((riskklass = ANY (ARRAY['lag'::text, 'normal'::text, 'hog'::text])));
alter table public.kyc_assessments add constraint kyc_assessments_status_check CHECK ((status = ANY (ARRAY['ej_paborjad'::text, 'pagaende'::text, 'godkand'::text, 'avslagen'::text])));
alter table public.kyc_assessments add constraint kyc_assessments_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id);
alter table public.kyc_assessments add constraint kyc_assessments_pkey PRIMARY KEY (id);
alter table public.lager_handelser add constraint lager_handelser_typ_check CHECK ((typ = ANY (ARRAY['inleverans'::text, 'utleverans'::text, 'justering'::text, 'inventering'::text])));
alter table public.lager_handelser add constraint lager_handelser_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.lager_handelser add constraint lager_handelser_inventering_id_fkey FOREIGN KEY (inventering_id) REFERENCES lager_inventeringar(id) ON DELETE SET NULL;
alter table public.lager_handelser add constraint lager_handelser_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES invoices(id) ON DELETE SET NULL;
alter table public.lager_handelser add constraint lager_handelser_leverans_id_fkey FOREIGN KEY (leverans_id) REFERENCES lager_leveranser(id) ON DELETE SET NULL;
alter table public.lager_handelser add constraint lager_handelser_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE;
alter table public.lager_handelser add constraint lager_handelser_supplier_invoice_id_fkey FOREIGN KEY (supplier_invoice_id) REFERENCES supplier_invoices(id) ON DELETE SET NULL;
alter table public.lager_handelser add constraint lager_handelser_pkey PRIMARY KEY (id);
alter table public.lager_inventering_rader add constraint lager_inventering_rader_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.lager_inventering_rader add constraint lager_inventering_rader_inventering_id_fkey FOREIGN KEY (inventering_id) REFERENCES lager_inventeringar(id) ON DELETE CASCADE;
alter table public.lager_inventering_rader add constraint lager_inventering_rader_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE;
alter table public.lager_inventering_rader add constraint lager_inventering_rader_pkey PRIMARY KEY (id);
alter table public.lager_inventering_rader add constraint lager_inventering_rader_inventering_id_product_id_key UNIQUE (inventering_id, product_id);
alter table public.lager_inventeringar add constraint lager_inventeringar_status_check CHECK ((status = ANY (ARRAY['under_planering'::text, 'paborjad'::text, 'slutford'::text, 'makulerad'::text])));
alter table public.lager_inventeringar add constraint lager_inventeringar_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.lager_inventeringar add constraint lager_inventeringar_pkey PRIMARY KEY (id);
alter table public.lager_inventeringar add constraint lager_inventeringar_company_id_nr_key UNIQUE (company_id, nr);
alter table public.lager_leveranser add constraint lager_leveranser_status_check CHECK ((status = ANY (ARRAY['ej_klar'::text, 'klar'::text, 'makulerad'::text])));
alter table public.lager_leveranser add constraint lager_leveranser_typ_check CHECK ((typ = ANY (ARRAY['inleverans'::text, 'utleverans'::text, 'lagerflytt'::text])));
alter table public.lager_leveranser add constraint lager_leveranser_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.lager_leveranser add constraint lager_leveranser_pkey PRIMARY KEY (id);
alter table public.lager_leveranser add constraint lager_leveranser_company_id_leveransnr_key UNIQUE (company_id, leveransnr);
alter table public.lonebesked add constraint lonebesked_run_id_fkey FOREIGN KEY (run_id) REFERENCES lonekorningar(id) ON DELETE CASCADE;
alter table public.lonebesked add constraint lonebesked_pkey PRIMARY KEY (id);
alter table public.lonekorningar add constraint lonekorningar_pkey PRIMARY KEY (id);
alter table public.mcp_audit_log add constraint mcp_audit_log_status_check CHECK ((status = ANY (ARRAY['ok'::text, 'fel'::text, 'nekad'::text])));
alter table public.mcp_audit_log add constraint mcp_audit_log_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE SET NULL;
alter table public.mcp_audit_log add constraint mcp_audit_log_pkey PRIMARY KEY (id);
alter table public.mcp_confirm_tokens add constraint mcp_confirm_tokens_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.mcp_confirm_tokens add constraint mcp_confirm_tokens_pkey PRIMARY KEY (id);
alter table public.monthly_control_comments add constraint monthly_control_comments_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.monthly_control_comments add constraint monthly_control_comments_item_id_fkey FOREIGN KEY (item_id) REFERENCES monthly_control_items(id) ON DELETE CASCADE;
alter table public.monthly_control_comments add constraint monthly_control_comments_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id);
alter table public.monthly_control_comments add constraint monthly_control_comments_pkey PRIMARY KEY (id);
alter table public.monthly_control_events add constraint monthly_control_events_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.monthly_control_events add constraint monthly_control_events_item_id_fkey FOREIGN KEY (item_id) REFERENCES monthly_control_items(id) ON DELETE CASCADE;
alter table public.monthly_control_events add constraint monthly_control_events_monthly_control_id_fkey FOREIGN KEY (monthly_control_id) REFERENCES monthly_controls(id) ON DELETE CASCADE;
alter table public.monthly_control_events add constraint monthly_control_events_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id);
alter table public.monthly_control_events add constraint monthly_control_events_pkey PRIMARY KEY (id);
alter table public.monthly_control_items add constraint monthly_control_items_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES auth.users(id);
alter table public.monthly_control_items add constraint monthly_control_items_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.monthly_control_items add constraint monthly_control_items_monthly_control_id_fkey FOREIGN KEY (monthly_control_id) REFERENCES monthly_controls(id) ON DELETE CASCADE;
alter table public.monthly_control_items add constraint monthly_control_items_resolved_by_fkey FOREIGN KEY (resolved_by) REFERENCES auth.users(id);
alter table public.monthly_control_items add constraint monthly_control_items_pkey PRIMARY KEY (id);
alter table public.monthly_controls add constraint monthly_controls_month_check CHECK (((month >= 1) AND (month <= 12)));
alter table public.monthly_controls add constraint monthly_controls_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.monthly_controls add constraint monthly_controls_pkey PRIMARY KEY (id);
alter table public.monthly_controls add constraint monthly_controls_company_id_year_month_key UNIQUE (company_id, year, month);
alter table public.notification_deliveries add constraint notification_deliveries_queue_id_fkey FOREIGN KEY (queue_id) REFERENCES notification_queue(id) ON DELETE CASCADE;
alter table public.notification_deliveries add constraint notification_deliveries_pkey PRIMARY KEY (id);
alter table public.notification_deliveries add constraint notification_deliveries_queue_id_key UNIQUE (queue_id);
alter table public.notification_events add constraint notification_events_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.notification_events add constraint notification_events_pkey PRIMARY KEY (id);
alter table public.notification_preferences add constraint notification_preferences_channel_check CHECK ((channel = ANY (ARRAY['in_app'::text, 'email'::text, 'sms'::text, 'push'::text])));
alter table public.notification_preferences add constraint notification_preferences_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.notification_preferences add constraint notification_preferences_pkey PRIMARY KEY (id);
alter table public.notification_preferences add constraint notification_preferences_user_id_company_id_event_type_chan_key UNIQUE (user_id, company_id, event_type, channel);
alter table public.notification_provider_logs add constraint notification_provider_logs_pkey PRIMARY KEY (id);
alter table public.notification_queue add constraint notification_queue_channel_check CHECK ((channel = ANY (ARRAY['in_app'::text, 'email'::text, 'sms'::text, 'push'::text])));
alter table public.notification_queue add constraint notification_queue_priority_check CHECK ((priority = ANY (ARRAY['low'::text, 'normal'::text, 'high'::text, 'urgent'::text])));
alter table public.notification_queue add constraint notification_queue_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'processing'::text, 'sent'::text, 'failed'::text, 'cancelled'::text, 'skipped'::text])));
alter table public.notification_queue add constraint notification_queue_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.notification_queue add constraint notification_queue_event_id_fkey FOREIGN KEY (event_id) REFERENCES notification_events(id) ON DELETE CASCADE;
alter table public.notification_queue add constraint notification_queue_pkey PRIMARY KEY (id);
alter table public.notification_queue add constraint notification_queue_idempotency_key_key UNIQUE (idempotency_key);
alter table public.notification_subscriptions add constraint notification_subscriptions_channel_check CHECK ((channel = ANY (ARRAY['sms'::text, 'push'::text])));
alter table public.notification_subscriptions add constraint notification_subscriptions_pkey PRIMARY KEY (id);
alter table public.notification_templates add constraint notification_templates_channel_check CHECK ((channel = ANY (ARRAY['in_app'::text, 'email'::text, 'sms'::text, 'push'::text])));
alter table public.notification_templates add constraint notification_templates_pkey PRIMARY KEY (id);
alter table public.notification_templates add constraint notification_templates_event_type_channel_lang_key UNIQUE (event_type, channel, lang);
alter table public.ocr_provider_config add constraint ocr_provider_config_singleton CHECK (id);
alter table public.ocr_provider_config add constraint ocr_provider_config_pkey PRIMARY KEY (id);
alter table public.platform_admins add constraint platform_admins_pkey PRIMARY KEY (email);
alter table public.platform_audit_log add constraint platform_audit_log_pkey PRIMARY KEY (id);
alter table public.platform_user_roles add constraint platform_user_roles_role_check CHECK ((role = ANY (ARRAY['superadmin'::text, 'operations_admin'::text, 'support_admin'::text, 'billing_admin'::text])));
alter table public.platform_user_roles add constraint platform_user_roles_pkey PRIMARY KEY (id);
alter table public.platform_user_roles add constraint platform_user_roles_email_role_key UNIQUE (email, role);
alter table public.products add constraint products_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.products add constraint products_pkey PRIMARY KEY (id);
alter table public.robo_bp_audit_log add constraint robo_bp_audit_log_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.robo_bp_audit_log add constraint robo_bp_audit_log_pkey PRIMARY KEY (id);
alter table public.robo_bp_checks add constraint robo_bp_checks_decision_basis_check CHECK (((decision_basis IS NULL) OR (decision_basis = ANY (ARRAY['system_observation'::text, 'ai_finding'::text]))));
alter table public.robo_bp_checks add constraint robo_bp_checks_risk_level_check CHECK ((risk_level = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text, 'critical'::text])));
alter table public.robo_bp_checks add constraint robo_bp_checks_status_check CHECK ((status = ANY (ARRAY['open'::text, 'in_progress'::text, 'done'::text, 'dismissed'::text])));
alter table public.robo_bp_checks add constraint robo_bp_checks_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.robo_bp_checks add constraint robo_bp_checks_pkey PRIMARY KEY (id);
alter table public.robo_bp_control_runs add constraint robo_bp_control_runs_status_check CHECK ((status = ANY (ARRAY['running'::text, 'done'::text, 'error'::text])));
alter table public.robo_bp_control_runs add constraint robo_bp_control_runs_pkey PRIMARY KEY (id);
alter table public.robo_bp_conversations add constraint robo_bp_conversations_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.robo_bp_conversations add constraint robo_bp_conversations_pkey PRIMARY KEY (id);
alter table public.robo_bp_conversations add constraint robo_bp_conversations_id_company_key UNIQUE (id, company_id);
alter table public.robo_bp_messages add constraint robo_bp_messages_risk_level_check CHECK ((risk_level = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text, 'critical'::text])));
alter table public.robo_bp_messages add constraint robo_bp_messages_role_check CHECK ((role = ANY (ARRAY['user'::text, 'assistant'::text])));
alter table public.robo_bp_messages add constraint robo_bp_messages_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.robo_bp_messages add constraint robo_bp_messages_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES robo_bp_conversations(id) ON DELETE CASCADE;
alter table public.robo_bp_messages add constraint robo_bp_messages_konv_bolag_fkey FOREIGN KEY (conversation_id, company_id) REFERENCES robo_bp_conversations(id, company_id) ON DELETE CASCADE;
alter table public.robo_bp_messages add constraint robo_bp_messages_pkey PRIMARY KEY (id);
alter table public.robo_bp_rules add constraint robo_bp_rules_source_check CHECK ((source = ANY (ARRAY['historik'::text, 'anvandarbekraftelse'::text, 'regelmotor'::text])));
alter table public.robo_bp_rules add constraint robo_bp_rules_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.robo_bp_rules add constraint robo_bp_rules_pkey PRIMARY KEY (id);
alter table public.robo_bp_settings add constraint robo_bp_settings_moms_period_check CHECK (((moms_period IS NULL) OR (moms_period = ANY (ARRAY['manadsvis'::text, 'kvartalsvis'::text, 'arsvis'::text]))));
alter table public.robo_bp_settings add constraint robo_bp_settings_sensitivity_check CHECK ((sensitivity = ANY (ARRAY['standard'::text, 'utokad'::text, 'anpassad'::text])));
alter table public.robo_bp_settings add constraint robo_bp_settings_pkey PRIMARY KEY (company_id);
alter table public.salaries add constraint salaries_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.salaries add constraint salaries_pkey PRIMARY KEY (id);
alter table public.sie_imports add constraint sie_imports_status_check CHECK ((status = ANY (ARRAY['imported'::text, 'angrad'::text])));
alter table public.sie_imports add constraint sie_imports_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.sie_imports add constraint sie_imports_pkey PRIMARY KEY (id);
alter table public.skattekonto_regler add constraint skattekonto_regler_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.skattekonto_regler add constraint skattekonto_regler_pkey PRIMARY KEY (id);
alter table public.stripe_event_log add constraint stripe_event_log_pkey PRIMARY KEY (event_id);
alter table public.subscription_plans add constraint subscription_plans_pkey PRIMARY KEY (id);
alter table public.supplier_accounting_rules add constraint supplier_accounting_rules_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.supplier_accounting_rules add constraint supplier_accounting_rules_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE CASCADE;
alter table public.supplier_accounting_rules add constraint supplier_accounting_rules_pkey PRIMARY KEY (id);
alter table public.supplier_invoices add constraint supplier_invoices_currency_chk CHECK (((currency IS NULL) OR (currency = ANY (ARRAY['SEK'::text, 'USD'::text, 'GBP'::text, 'EUR'::text]))));
alter table public.supplier_invoices add constraint supplier_invoices_momstyp_check CHECK ((momstyp = ANY (ARRAY['normal'::text, 'omvand_bygg'::text, 'eu_forvarv'::text, 'import'::text])));
alter table public.supplier_invoices add constraint supplier_invoices_betalning_ver_id_fkey FOREIGN KEY (betalning_ver_id) REFERENCES verifikationer(id) ON DELETE SET NULL;
alter table public.supplier_invoices add constraint supplier_invoices_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.supplier_invoices add constraint supplier_invoices_document_id_fkey FOREIGN KEY (document_id) REFERENCES documents(id);
alter table public.supplier_invoices add constraint supplier_invoices_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES suppliers(id);
alter table public.supplier_invoices add constraint supplier_invoices_verifikation_id_fkey FOREIGN KEY (verifikation_id) REFERENCES verifikationer(id) ON DELETE SET NULL;
alter table public.supplier_invoices add constraint supplier_invoices_pkey PRIMARY KEY (id);
alter table public.suppliers add constraint suppliers_valuta_chk CHECK (((valuta IS NULL) OR (valuta = ANY (ARRAY['SEK'::text, 'USD'::text, 'GBP'::text, 'EUR'::text]))));
alter table public.suppliers add constraint suppliers_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.suppliers add constraint suppliers_pkey PRIMARY KEY (id);
alter table public.support_ai_events add constraint support_ai_events_pkey PRIMARY KEY (id);
alter table public.support_attachments add constraint support_attachments_visibility_check CHECK ((visibility = ANY (ARRAY['customer_visible'::text, 'internal_only'::text])));
alter table public.support_attachments add constraint support_attachments_message_id_fkey FOREIGN KEY (message_id) REFERENCES support_messages(id) ON DELETE CASCADE;
alter table public.support_attachments add constraint support_attachments_note_id_fkey FOREIGN KEY (note_id) REFERENCES support_internal_notes(id) ON DELETE CASCADE;
alter table public.support_attachments add constraint support_attachments_ticket_id_fkey FOREIGN KEY (ticket_id) REFERENCES support_tickets(id) ON DELETE CASCADE;
alter table public.support_attachments add constraint support_attachments_pkey PRIMARY KEY (id);
alter table public.support_internal_notes add constraint support_internal_notes_ticket_id_fkey FOREIGN KEY (ticket_id) REFERENCES support_tickets(id) ON DELETE CASCADE;
alter table public.support_internal_notes add constraint support_internal_notes_pkey PRIMARY KEY (id);
alter table public.support_messages add constraint support_messages_ticket_id_fkey FOREIGN KEY (ticket_id) REFERENCES support_tickets(id) ON DELETE CASCADE;
alter table public.support_messages add constraint support_messages_pkey PRIMARY KEY (id);
alter table public.support_reads add constraint support_reads_ticket_id_fkey FOREIGN KEY (ticket_id) REFERENCES support_tickets(id) ON DELETE CASCADE;
alter table public.support_reads add constraint support_reads_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.support_reads add constraint support_reads_pkey PRIMARY KEY (ticket_id, user_id);
alter table public.support_tickets add constraint support_tickets_category_check CHECK ((category = ANY (ARRAY['billing'::text, 'invoice_import'::text, 'bookkeeping'::text, 'login_access'::text, 'technical_error'::text, 'feature_request'::text, 'other'::text])));
alter table public.support_tickets add constraint support_tickets_priority_check CHECK ((priority = ANY (ARRAY['low'::text, 'normal'::text, 'high'::text, 'urgent'::text])));
alter table public.support_tickets add constraint support_tickets_status_check CHECK ((status = ANY (ARRAY['new'::text, 'open'::text, 'waiting_for_customer'::text, 'waiting_for_support'::text, 'resolved'::text, 'closed'::text])));
alter table public.support_tickets add constraint support_tickets_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.support_tickets add constraint support_tickets_pkey PRIMARY KEY (id);
alter table public.swish_regler add constraint swish_regler_check CHECK ((max_belopp >= min_belopp));
alter table public.swish_regler add constraint swish_regler_min_belopp_check CHECK ((min_belopp >= (0)::numeric));
alter table public.swish_regler add constraint swish_regler_momssats_check CHECK ((momssats = ANY (ARRAY[(0)::numeric, (6)::numeric, (12)::numeric, (25)::numeric])));
alter table public.swish_regler add constraint swish_regler_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.swish_regler add constraint swish_regler_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE;
alter table public.swish_regler add constraint swish_regler_pkey PRIMARY KEY (id);
alter table public.system_error_log add constraint system_error_log_pkey PRIMARY KEY (id);
alter table public.uppdrag add constraint uppdrag_bokforingstakt_check CHECK ((bokforingstakt = ANY (ARRAY['dag'::text, 'manad'::text, 'kvartal'::text, 'rakenskapsar'::text])));
alter table public.uppdrag add constraint uppdrag_check CHECK (((bokforingstakt IS NULL) OR (uppdragstyp = 'lopande_bokforing'::text)));
alter table public.uppdrag add constraint uppdrag_check1 CHECK (((NOT revisionsplikt) OR (uppdragstyp = 'bokslut'::text)));
alter table public.uppdrag add constraint uppdrag_check2 CHECK (((NOT byraanstand_aktiv) OR (uppdragstyp = ANY (ARRAY['momsdeklaration'::text, 'inkomstdeklaration'::text]))));
alter table public.uppdrag add constraint uppdrag_status_check CHECK ((status = ANY (ARRAY['aktiv'::text, 'pausad'::text, 'avslutad'::text])));
alter table public.uppdrag add constraint uppdrag_uppdragstyp_check CHECK ((uppdragstyp = ANY (ARRAY['lopande_bokforing'::text, 'momsdeklaration'::text, 'lon_agi'::text, 'bokslut'::text, 'arsredovisning'::text, 'inkomstdeklaration'::text])));
alter table public.uppdrag add constraint uppdrag_byra_bolag_id_fkey FOREIGN KEY (byra_bolag_id) REFERENCES companies(id) ON DELETE RESTRICT;
alter table public.uppdrag add constraint uppdrag_byra_klient_id_fkey FOREIGN KEY (byra_klient_id) REFERENCES byra_klient(id) ON DELETE RESTRICT;
alter table public.uppdrag add constraint uppdrag_klient_bolag_id_fkey FOREIGN KEY (klient_bolag_id) REFERENCES companies(id) ON DELETE RESTRICT;
alter table public.uppdrag add constraint uppdrag_pkey PRIMARY KEY (id);
alter table public.uppdrag add constraint uppdrag_byra_klient_id_uppdragstyp_key UNIQUE (byra_klient_id, uppdragstyp);
alter table public.uppdragsuppgift add constraint uppdragsuppgift_status_check CHECK ((status = ANY (ARRAY['ej_paborjad'::text, 'pagar'::text, 'klar'::text, 'forsenad'::text])));
alter table public.uppdragsuppgift add constraint uppdragsuppgift_byra_bolag_id_fkey FOREIGN KEY (byra_bolag_id) REFERENCES companies(id) ON DELETE RESTRICT;
alter table public.uppdragsuppgift add constraint uppdragsuppgift_klient_bolag_id_fkey FOREIGN KEY (klient_bolag_id) REFERENCES companies(id) ON DELETE RESTRICT;
alter table public.uppdragsuppgift add constraint uppdragsuppgift_uppdrag_id_fkey FOREIGN KEY (uppdrag_id) REFERENCES uppdrag(id) ON DELETE RESTRICT;
alter table public.uppdragsuppgift add constraint uppdragsuppgift_pkey PRIMARY KEY (id);
alter table public.uppdragsuppgift add constraint uppdragsuppgift_uppdrag_id_period_start_key UNIQUE (uppdrag_id, period_start);
alter table public.user_companies add constraint user_companies_role_check CHECK ((role = ANY (ARRAY['admin'::text, 'member'::text])));
alter table public.user_companies add constraint user_companies_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.user_companies add constraint user_companies_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.user_companies add constraint user_companies_pkey PRIMARY KEY (id);
alter table public.user_companies add constraint user_companies_user_id_company_id_key UNIQUE (user_id, company_id);
alter table public.vat_reports add constraint vat_reports_month_check CHECK (((month >= 1) AND (month <= 12)));
alter table public.vat_reports add constraint vat_reports_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.vat_reports add constraint vat_reports_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id);
alter table public.vat_reports add constraint vat_reports_verifikation_id_fkey FOREIGN KEY (verifikation_id) REFERENCES verifikationer(id) ON DELETE SET NULL;
alter table public.vat_reports add constraint vat_reports_pkey PRIMARY KEY (id);
alter table public.vat_reports add constraint vat_reports_company_id_year_month_key UNIQUE (company_id, year, month);
alter table public.verifikation_andringar add constraint verifikation_andringar_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.verifikation_andringar add constraint verifikation_andringar_original_id_fkey FOREIGN KEY (original_id) REFERENCES verifikationer(id) ON DELETE CASCADE;
alter table public.verifikation_andringar add constraint verifikation_andringar_rattelse_id_fkey FOREIGN KEY (rattelse_id) REFERENCES verifikationer(id) ON DELETE SET NULL;
alter table public.verifikation_andringar add constraint verifikation_andringar_pkey PRIMARY KEY (id);
alter table public.verifikation_rows add constraint verifikation_rows_verifikation_id_fkey FOREIGN KEY (verifikation_id) REFERENCES verifikationer(id) ON DELETE CASCADE;
alter table public.verifikation_rows add constraint verifikation_rows_pkey PRIMARY KEY (id);
alter table public.verifikationer add constraint verifikationer_status_chk CHECK ((status = ANY (ARRAY['aktiv'::text, 'makulerad'::text, 'motverifikation'::text, 'rattad'::text, 'rattelse'::text])));
alter table public.verifikationer add constraint verifikationer_company_id_fkey FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE;
alter table public.verifikationer add constraint verifikationer_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id);
alter table public.verifikationer add constraint verifikationer_ersatter_fkey FOREIGN KEY (ersatter) REFERENCES verifikationer(id);
alter table public.verifikationer add constraint verifikationer_makulerad_av_fkey FOREIGN KEY (makulerad_av) REFERENCES verifikationer(id);
alter table public.verifikationer add constraint verifikationer_motverkar_fkey FOREIGN KEY (motverkar) REFERENCES verifikationer(id);
alter table public.verifikationer add constraint verifikationer_rattad_av_fkey FOREIGN KEY (rattad_av) REFERENCES verifikationer(id);
alter table public.verifikationer add constraint verifikationer_rattar_fkey FOREIGN KEY (rattar) REFERENCES verifikationer(id);
alter table public.verifikationer add constraint verifikationer_sie_import_id_fkey FOREIGN KEY (sie_import_id) REFERENCES sie_imports(id);
alter table public.verifikationer add constraint verifikationer_pkey PRIMARY KEY (id);
alter table public.verifikationer add constraint verifikationer_company_id_ver_nr_key UNIQUE (company_id, ver_nr);
alter table public.worker_health add constraint worker_health_pkey PRIMARY KEY (component);
