CREATE INDEX aib_company_idx ON public.account_import_batches USING btree (company_id, created_at DESC);
CREATE INDEX agi_deklarationer_company_idx ON public.agi_deklarationer USING btree (company_id, period);
CREATE INDEX idx_ai_bokforing_logg_company ON public.ai_bokforing_logg USING btree (company_id, created_at DESC);
CREATE INDEX idx_ai_bokforing_logg_document_id ON public.ai_bokforing_logg USING btree (document_id);
CREATE INDEX idx_ai_logg_verifikation ON public.ai_bokforing_logg USING btree (verifikation_id) WHERE (verifikation_id IS NOT NULL);
CREATE INDEX ai_call_log_recent_idx ON public.ai_call_log USING btree (created_at);
CREATE INDEX ai_checklista_korningar_idx ON public.ai_checklista_korningar USING btree (company_id, created_at DESC);
CREATE INDEX ai_cooldowns_until_idx ON public.ai_cooldowns USING btree (cooldown_until);
CREATE INDEX ai_error_log_doc_idx ON public.ai_error_log USING btree (document_id, created_at DESC);
CREATE INDEX ai_usage_company_idx ON public.ai_usage_log USING btree (company_id, created_at);
CREATE INDEX aml_flags_company_status_idx ON public.aml_flags USING btree (company_id, status);
CREATE INDEX annual_report_sections_draft_idx ON public.annual_report_draft_sections USING btree (draft_id, sort_order);
CREATE INDEX idx_annual_report_draft_sections_company_id ON public.annual_report_draft_sections USING btree (company_id);
CREATE INDEX annual_report_drafts_company_idx ON public.annual_report_drafts USING btree (company_id, status);
CREATE INDEX idx_annual_report_drafts_fiscal_year_id ON public.annual_report_drafts USING btree (fiscal_year_id);
CREATE INDEX ar_exports_draft_idx ON public.annual_report_exports USING btree (draft_id, created_at DESC);
CREATE INDEX idx_annual_report_exports_company_id ON public.annual_report_exports USING btree (company_id);
CREATE INDEX idx_annual_report_exports_engagement_id ON public.annual_report_exports USING btree (engagement_id);
CREATE INDEX ar_validation_draft_idx ON public.annual_report_validation_items USING btree (draft_id, status, severity);
CREATE INDEX idx_annual_report_validation_items_company_id ON public.annual_report_validation_items USING btree (company_id);
CREATE INDEX idx_annual_report_validation_items_engagement_id ON public.annual_report_validation_items USING btree (engagement_id);
CREATE INDEX idx_annual_report_validation_items_section_id ON public.annual_report_validation_items USING btree (section_id);
CREATE UNIQUE INDEX arkiv_filer_doc_uniq ON public.arkiv_filer USING btree (mapp_id, document_id) WHERE ((document_id IS NOT NULL) AND (raderad_at IS NULL));
CREATE INDEX arkiv_filer_document_idx ON public.arkiv_filer USING btree (document_id) WHERE (document_id IS NOT NULL);
CREATE INDEX arkiv_filer_mapp_idx ON public.arkiv_filer USING btree (company_id, mapp_id, raderad_at);
CREATE UNIQUE INDEX arkiv_mappar_namn_uniq ON public.arkiv_mappar USING btree (company_id, COALESCE(parent_id, '00000000-0000-0000-0000-000000000000'::uuid), lower(btrim(namn)));
CREATE UNIQUE INDEX arkiv_mappar_systemnyckel_uniq ON public.arkiv_mappar USING btree (company_id, systemnyckel) WHERE (systemnyckel IS NOT NULL);
CREATE INDEX arkiv_mappar_traed_idx ON public.arkiv_mappar USING btree (company_id, parent_id);
CREATE INDEX idx_arkiv_mappar_parent_id ON public.arkiv_mappar USING btree (parent_id);
CREATE INDEX article_templates_company_idx ON public.article_templates USING btree (company_id);
CREATE INDEX assistent_logg_company_manad ON public.assistent_logg USING btree (company_id, created_at);
CREATE INDEX audit_log_company_idx ON public.audit_log USING btree (company_id, created_at DESC);
CREATE UNIQUE INDEX bank_accounts_company_account_nr_unik ON public.bank_accounts USING btree (company_id, account_nr);
CREATE INDEX idx_bank_transactions_company_id ON public.bank_transactions USING btree (company_id);
CREATE INDEX idx_bank_transactions_verifikation_id ON public.bank_transactions USING btree (verifikation_id);
CREATE UNIQUE INDEX beta_ansokningar_en_vantande ON public.beta_ansokningar USING btree (user_id) WHERE (status = 'vantar'::text);
CREATE INDEX beta_ansokningar_status_idx ON public.beta_ansokningar USING btree (status, created_at DESC);
CREATE INDEX idx_beta_ansokningar_company_id ON public.beta_ansokningar USING btree (company_id);
CREATE INDEX bokslut_ai_suggestions_company ON public.bokslut_ai_suggestions USING btree (company_id, status);
CREATE INDEX bokslut_ai_suggestions_engagement ON public.bokslut_ai_suggestions USING btree (engagement_id);
CREATE INDEX idx_bokslut_ai_suggestions_related_attachment_id ON public.bokslut_ai_suggestions USING btree (related_attachment_id);
CREATE INDEX idx_bokslut_ai_suggestions_related_check_id ON public.bokslut_ai_suggestions USING btree (related_check_id);
CREATE INDEX idx_bokslut_ai_suggestions_reviewed_by ON public.bokslut_ai_suggestions USING btree (reviewed_by);
CREATE INDEX bokslut_attachments_check ON public.bokslut_attachments USING btree (check_id);
CREATE INDEX bokslut_attachments_company ON public.bokslut_attachments USING btree (company_id, status);
CREATE INDEX bokslut_attachments_engagement ON public.bokslut_attachments USING btree (engagement_id);
CREATE INDEX idx_bokslut_attachments_created_by ON public.bokslut_attachments USING btree (created_by);
CREATE INDEX idx_bokslut_attachments_reviewed_by ON public.bokslut_attachments USING btree (reviewed_by);
CREATE INDEX bokslut_audit_engagement ON public.bokslut_audit_log USING btree (engagement_id, created_at);
CREATE INDEX idx_bokslut_audit_log_company_id ON public.bokslut_audit_log USING btree (company_id);
CREATE INDEX idx_bokslut_audit_log_user_id ON public.bokslut_audit_log USING btree (user_id);
CREATE INDEX bokslut_checks_company ON public.bokslut_checks USING btree (company_id, status, risk_level);
CREATE UNIQUE INDEX bokslut_checks_uniq ON public.bokslut_checks USING btree (engagement_id, rule_key, COALESCE(account_nr, '-'::text));
CREATE INDEX idx_bokslut_checks_assigned_to ON public.bokslut_checks USING btree (assigned_to);
CREATE INDEX idx_bokslut_checks_resolved_by ON public.bokslut_checks USING btree (resolved_by);
CREATE INDEX bokslut_denied_log_company ON public.bokslut_denied_log USING btree (company_id, created_at DESC);
CREATE INDEX bokslut_denied_log_user ON public.bokslut_denied_log USING btree (user_id, created_at DESC);
CREATE INDEX idx_bokslut_engagements_ansvarig_user_id ON public.bokslut_engagements USING btree (ansvarig_user_id);
CREATE INDEX idx_bokslut_engagements_fiscal_year_id ON public.bokslut_engagements USING btree (fiscal_year_id);
CREATE INDEX bokslut_sync_ops_expires_idx ON public.bokslut_sync_operations USING btree (expires_at);
CREATE INDEX bookkeeping_templates_company_idx ON public.bookkeeping_templates USING btree (company_id);
CREATE INDEX byra_klient_byra_idx ON public.byra_klient USING btree (byra_bolag_id, status);
CREATE INDEX idx_byra_klient_klient_bolag_id ON public.byra_klient USING btree (klient_bolag_id);
CREATE UNIQUE INDEX companies_archive_number_key ON public.companies USING btree (archive_number);
CREATE UNIQUE INDEX companies_company_number_key ON public.companies USING btree (company_number);
CREATE INDEX idx_company_invites_company_id ON public.company_invites USING btree (company_id);
CREATE INDEX idx_company_invites_invited_by ON public.company_invites USING btree (invited_by);
CREATE INDEX cs_plan_idx ON public.company_subscriptions USING btree (plan_id);
CREATE INDEX cs_status_idx ON public.company_subscriptions USING btree (status);
CREATE UNIQUE INDEX customers_company_kundnr_uniq ON public.customers USING btree (company_id, kund_nr) WHERE (kund_nr IS NOT NULL);
CREATE UNIQUE INDEX customers_company_orgnr_uniq ON public.customers USING btree (company_id, org_nr_normalized) WHERE (org_nr_normalized IS NOT NULL);
CREATE UNIQUE INDEX deadline_regel_nyckel_idx ON public.deadline_regel USING btree (uppgiftstyp, COALESCE(bolagsform, ''::text), COALESCE(variant, ''::text), giltig_fran);
CREATE INDEX documents_company_created_idx ON public.documents USING btree (company_id, created_at);
CREATE INDEX idx_documents_import_batch ON public.documents USING btree (import_batch) WHERE (import_batch IS NOT NULL);
CREATE INDEX idx_documents_verifikation_id ON public.documents USING btree (verifikation_id);
CREATE INDEX employees_company_idx ON public.employees USING btree (company_id, is_active);
CREATE INDEX idx_extraction_corrections_document_id ON public.extraction_corrections USING btree (document_id);
CREATE INDEX idx_extraction_corrections_supplier ON public.extraction_corrections USING btree (company_id, supplier_id, field);
CREATE INDEX idx_extraction_corrections_supplier_id ON public.extraction_corrections USING btree (supplier_id);
CREATE INDEX help_feedback_article_idx ON public.help_feedback USING btree (article_slug, created_at DESC);
CREATE INDEX inbound_email_log_company_idx ON public.inbound_email_log USING btree (company_id, created_at DESC);
CREATE UNIQUE INDEX inbound_email_log_message_id_key ON public.inbound_email_log USING btree (message_id) WHERE (message_id IS NOT NULL);
CREATE INDEX inbox_addresses_company_idx ON public.inbox_addresses USING btree (company_id);
CREATE INDEX idx_inkommande_gods_leverans_id ON public.inkommande_gods USING btree (leverans_id);
CREATE INDEX idx_inkommande_gods_order_id ON public.inkommande_gods USING btree (order_id);
CREATE INDEX idx_inkopsorder_rader_company_id ON public.inkopsorder_rader USING btree (company_id);
CREATE INDEX idx_inkopsorder_rader_product_id ON public.inkopsorder_rader USING btree (product_id);
CREATE INDEX inkopsorder_rader_order_idx ON public.inkopsorder_rader USING btree (order_id);
CREATE INDEX idx_inkopsordrar_supplier_id ON public.inkopsordrar USING btree (supplier_id);
CREATE INDEX idx_invoice_rows_invoice_id ON public.invoice_rows USING btree (invoice_id);
CREATE INDEX idx_invoice_rows_product_id ON public.invoice_rows USING btree (product_id);
CREATE INDEX idx_invoices_customer_id ON public.invoices USING btree (customer_id);
CREATE INDEX idx_invoices_krediterar ON public.invoices USING btree (krediterar_id) WHERE (krediterar_id IS NOT NULL);
CREATE INDEX idx_invoices_verifikation_id ON public.invoices USING btree (verifikation_id);
CREATE INDEX invoices_betalning_ver_id_idx ON public.invoices USING btree (betalning_ver_id) WHERE (betalning_ver_id IS NOT NULL);
CREATE INDEX invoices_company_created_idx ON public.invoices USING btree (company_id, created_at);
CREATE INDEX kivra_utskick_ref_idx ON public.kivra_utskick USING btree (company_id, typ, referens_id);
CREATE INDEX konsol_abonnemangsfakturor_company_idx ON public.konsol_abonnemangsfakturor USING btree (company_id, fakturadatum DESC);
CREATE INDEX idx_konsol_arenden_company_id ON public.konsol_arenden USING btree (company_id);
CREATE INDEX konsol_arenden_oppna_idx ON public.konsol_arenden USING btree (status, prioritet, updated_at DESC);
CREATE INDEX konsol_audit_company_idx ON public.konsol_audit_logg USING btree (company_id, created_at DESC);
CREATE INDEX konsol_audit_created_idx ON public.konsol_audit_logg USING btree (created_at DESC);
CREATE INDEX konsol_kundanteckningar_company_idx ON public.konsol_kundanteckningar USING btree (company_id, created_at DESC);
CREATE INDEX konsol_livscykel_company_idx ON public.konsol_livscykel_steg USING btree (company_id);
CREATE INDEX konsol_support_samtycken_company_idx ON public.konsol_support_samtycken USING btree (company_id, giltig_till DESC);
CREATE INDEX kyc_arkiv_bevaras_idx ON public.kyc_arkiv USING btree (bevaras_till);
CREATE INDEX kyc_arkiv_byra_idx ON public.kyc_arkiv USING gin (byra_bolag_ids);
CREATE INDEX kyc_assessments_company_idx ON public.kyc_assessments USING btree (company_id, created_at DESC);
CREATE INDEX idx_kyc_bilagor_company_id ON public.kyc_bilagor USING btree (company_id);
CREATE INDEX idx_kyc_bilagor_kyc_id ON public.kyc_bilagor USING btree (kyc_id);
CREATE INDEX idx_kyc_huvudman_company_id ON public.kyc_huvudman USING btree (company_id);
CREATE INDEX idx_kyc_huvudman_kyc_id ON public.kyc_huvudman USING btree (kyc_id);
CREATE INDEX idx_lager_handelser_inventering_id ON public.lager_handelser USING btree (inventering_id);
CREATE INDEX idx_lager_handelser_invoice_id ON public.lager_handelser USING btree (invoice_id);
CREATE INDEX idx_lager_handelser_product_id ON public.lager_handelser USING btree (product_id);
CREATE INDEX idx_lager_handelser_supplier_invoice_id ON public.lager_handelser USING btree (supplier_invoice_id);
CREATE INDEX lager_handelser_batch_idx ON public.lager_handelser USING btree (company_id, batchnr) WHERE (batchnr IS NOT NULL);
CREATE INDEX lager_handelser_idx ON public.lager_handelser USING btree (company_id, product_id, datum);
CREATE INDEX lager_handelser_leverans_idx ON public.lager_handelser USING btree (leverans_id);
CREATE INDEX idx_lager_inventering_rader_company_id ON public.lager_inventering_rader USING btree (company_id);
CREATE INDEX idx_lager_inventering_rader_product_id ON public.lager_inventering_rader USING btree (product_id);
CREATE INDEX lonebesked_company_idx ON public.lonebesked USING btree (company_id);
CREATE INDEX lonebesked_run_idx ON public.lonebesked USING btree (run_id);
CREATE INDEX lonekorningar_company_idx ON public.lonekorningar USING btree (company_id, period);
CREATE INDEX lonekorningar_ver_idx ON public.lonekorningar USING btree (verifikation_id);
CREATE INDEX mcp_audit_log_company_idx ON public.mcp_audit_log USING btree (company_id, created_at DESC);
CREATE UNIQUE INDEX mcp_tokens_idempotens_idx ON public.mcp_confirm_tokens USING btree (company_id, idempotency_key) WHERE ((used_at IS NOT NULL) AND (idempotency_key IS NOT NULL));
CREATE INDEX idx_monthly_control_comments_company_id ON public.monthly_control_comments USING btree (company_id);
CREATE INDEX idx_monthly_control_comments_user_id ON public.monthly_control_comments USING btree (user_id);
CREATE INDEX monthly_control_comments_item ON public.monthly_control_comments USING btree (item_id, created_at);
CREATE INDEX idx_monthly_control_events_company_id ON public.monthly_control_events USING btree (company_id);
CREATE INDEX idx_monthly_control_events_user_id ON public.monthly_control_events USING btree (user_id);
CREATE INDEX monthly_control_events_control ON public.monthly_control_events USING btree (monthly_control_id, created_at);
CREATE INDEX monthly_control_events_item ON public.monthly_control_events USING btree (item_id, created_at);
CREATE INDEX idx_monthly_control_items_assigned_to ON public.monthly_control_items USING btree (assigned_to);
CREATE INDEX idx_monthly_control_items_resolved_by ON public.monthly_control_items USING btree (resolved_by);
CREATE INDEX monthly_control_items_company_status ON public.monthly_control_items USING btree (company_id, status, priority);
CREATE INDEX monthly_control_items_control ON public.monthly_control_items USING btree (monthly_control_id);
CREATE UNIQUE INDEX monthly_control_items_uniq ON public.monthly_control_items USING btree (monthly_control_id, rule_key, COALESCE(related_id, '00000000-0000-0000-0000-000000000000'::uuid));
CREATE UNIQUE INDEX nev_dedupe_idx ON public.notification_events USING btree (company_id, dedupe_key) WHERE (dedupe_key IS NOT NULL);
CREATE INDEX idx_notification_preferences_company_id ON public.notification_preferences USING btree (company_id);
CREATE INDEX idx_notification_queue_company_id ON public.notification_queue USING btree (company_id);
CREATE INDEX idx_notification_queue_event_id ON public.notification_queue USING btree (event_id);
CREATE INDEX nq_pending_idx ON public.notification_queue USING btree (status, scheduled_at) WHERE (status = ANY (ARRAY['pending'::text, 'failed'::text]));
CREATE INDEX nq_user_inapp_idx ON public.notification_queue USING btree (user_id, channel, read_at) WHERE (channel = 'in_app'::text);
CREATE INDEX idx_products_company_id ON public.products USING btree (company_id);
CREATE INDEX idx_robo_audit_company ON public.robo_bp_audit_log USING btree (company_id, created_at DESC);
CREATE INDEX idx_robo_checks_company ON public.robo_bp_checks USING btree (company_id, status, created_at DESC);
CREATE INDEX robo_bp_control_runs_company_idx ON public.robo_bp_control_runs USING btree (company_id, started_at DESC);
CREATE INDEX idx_robo_conv_company ON public.robo_bp_conversations USING btree (company_id, updated_at DESC);
CREATE INDEX idx_robo_bp_messages_company_id ON public.robo_bp_messages USING btree (company_id);
CREATE INDEX idx_robo_bp_messages_conversation_id_company_id ON public.robo_bp_messages USING btree (conversation_id, company_id);
CREATE INDEX idx_robo_msg_conv ON public.robo_bp_messages USING btree (conversation_id, created_at);
CREATE INDEX idx_robo_rules_company ON public.robo_bp_rules USING btree (company_id, active);
CREATE INDEX idx_salaries_company_id ON public.salaries USING btree (company_id);
CREATE INDEX idx_sie_imports_company ON public.sie_imports USING btree (company_id, created_at DESC);
CREATE INDEX idx_skattekonto_regler_company ON public.skattekonto_regler USING btree (company_id) WHERE aktiv;
CREATE INDEX idx_supplier_accounting_rules_lookup ON public.supplier_accounting_rules USING btree (company_id, supplier_id, status);
CREATE INDEX idx_supplier_accounting_rules_merchant ON public.supplier_accounting_rules USING btree (company_id, merchant_name, status);
CREATE INDEX idx_supplier_accounting_rules_supplier_id ON public.supplier_accounting_rules USING btree (supplier_id);
CREATE INDEX idx_supplier_invoices_betalning_ver_id ON public.supplier_invoices USING btree (betalning_ver_id);
CREATE INDEX idx_supplier_invoices_company_id ON public.supplier_invoices USING btree (company_id);
CREATE INDEX idx_supplier_invoices_document ON public.supplier_invoices USING btree (document_id) WHERE (document_id IS NOT NULL);
CREATE INDEX idx_supplier_invoices_supplier_id ON public.supplier_invoices USING btree (supplier_id);
CREATE INDEX idx_supplier_invoices_verifikation_id ON public.supplier_invoices USING btree (verifikation_id);
CREATE INDEX idx_suppliers_company_id ON public.suppliers USING btree (company_id);
CREATE INDEX support_ai_events_company_idx ON public.support_ai_events USING btree (company_id, created_at DESC);
CREATE INDEX idx_support_attachments_message_id ON public.support_attachments USING btree (message_id);
CREATE INDEX idx_support_attachments_note_id ON public.support_attachments USING btree (note_id);
CREATE INDEX idx_support_attachments_ticket_id ON public.support_attachments USING btree (ticket_id);
CREATE INDEX sin_ticket_idx ON public.support_internal_notes USING btree (ticket_id);
CREATE INDEX sm_ticket_idx ON public.support_messages USING btree (ticket_id);
CREATE INDEX idx_support_reads_user_id ON public.support_reads USING btree (user_id);
CREATE INDEX st_company_idx ON public.support_tickets USING btree (company_id);
CREATE INDEX st_status_idx ON public.support_tickets USING btree (status);
CREATE INDEX idx_swish_regler_company ON public.swish_regler USING btree (company_id) WHERE aktiv;
CREATE INDEX idx_swish_regler_customer_id ON public.swish_regler USING btree (customer_id);
CREATE INDEX system_error_log_recent_idx ON public.system_error_log USING btree (occurred_at DESC);
CREATE INDEX uppdrag_byra_idx ON public.uppdrag USING btree (byra_bolag_id, status);
CREATE INDEX uppdrag_klient_idx ON public.uppdrag USING btree (klient_bolag_id);
CREATE INDEX idx_uppdragsuppgift_klient_bolag_id ON public.uppdragsuppgift USING btree (klient_bolag_id);
CREATE INDEX uppgift_ansvarig_idx ON public.uppdragsuppgift USING btree (uppdragsansvarig_anvandare_id, status);
CREATE INDEX uppgift_byra_status_idx ON public.uppdragsuppgift USING btree (byra_bolag_id, status, COALESCE(justerat_forfallodatum, ordinarie_forfallodatum));
CREATE INDEX idx_user_companies_company_id ON public.user_companies USING btree (company_id);
CREATE INDEX idx_vat_reports_created_by ON public.vat_reports USING btree (created_by);
CREATE INDEX idx_vat_reports_verifikation_id ON public.vat_reports USING btree (verifikation_id);
CREATE INDEX idx_verifikation_andringar_company_id ON public.verifikation_andringar USING btree (company_id);
CREATE INDEX idx_verifikation_andringar_original_id ON public.verifikation_andringar USING btree (original_id);
CREATE INDEX idx_verifikation_andringar_rattelse_id ON public.verifikation_andringar USING btree (rattelse_id);
CREATE INDEX idx_verifikation_rows_verifikation_id ON public.verifikation_rows USING btree (verifikation_id);
CREATE INDEX idx_verifikationer_created_by ON public.verifikationer USING btree (created_by);
CREATE INDEX idx_verifikationer_ersatter ON public.verifikationer USING btree (ersatter);
CREATE INDEX idx_verifikationer_makulerad_av ON public.verifikationer USING btree (makulerad_av);
CREATE INDEX idx_verifikationer_motverkar ON public.verifikationer USING btree (motverkar);
CREATE INDEX idx_verifikationer_rattad_av ON public.verifikationer USING btree (rattad_av);
CREATE INDEX idx_verifikationer_rattar ON public.verifikationer USING btree (rattar);
CREATE INDEX idx_verifikationer_sie_import ON public.verifikationer USING btree (sie_import_id) WHERE (sie_import_id IS NOT NULL);
